### ISSUE TITLE
While statements. 

### ISSUE THREAD

**Issue by chtzvt** [AzuraDev/JSPrank#1]
Use "while(true)" instead of needlessly creating a variable. 

While is only looking for a true condition. That's all it needs to be satisfied.

**Comment by AzuraDev** [comment]
ill do that :D

**Comment by chtzvt** [comment]
Great!

**Comment by AzuraDev** [comment]
There you go its done

**Comment by AzuraDev** [comment]
Lol You know even in java i never really thought of that
